### PR TITLE
Use real DB in lambdas

### PR DESCRIPTION
**Pull request by Anisotropic**
TASK4: 

1 - Task 4.1 is implemented
3 - TASK 4.2 is implemented lambda links are provided and returns data
4 - TASK 4.3 is implemented lambda links are provided and products is stored in DB (call TASK 4.2 to see the product)
5 - Your own Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend. Link to a working Front-End application is provided for cross-check reviewer.

Additional (optional) tasks:

- POST/products lambda functions returns error 400 status code if product data is invalid
- All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
-  ~~All lambdas do console.log for each incoming requests and their arguments~~ No extra shit in logs!
-  ~~Transaction based creation of product (in case stock creation is failed then related to this stock product is not created and not ready to be used by the end user and vice versa) (https://devcenter.kinvey.com/nodejs/tutorials/bl-transactional-support)~~

==========================================================================

Deployed app: https://d2vqqselzzxqjs.cloudfront.net/
GET ALL lambda check: https://uv2t74mcu0.execute-api.eu-west-1.amazonaws.com/dev/products/
GET BY ID lambda check: https://uv2t74mcu0.execute-api.eu-west-1.amazonaws.com/dev/products/221cecef-1ecc-4f61-aaa6-9d0bce26ca64
Direct link to test creation of new product link: https://d2vqqselzzxqjs.cloudfront.net/admin/product-form/

===================

Corresponding FE PR: https://github.com/Anisotropic/nodejs-aws-fe/pull/3

### CODE REVIEW

**Comment by numatay** [comment]
Hi @Anisotropic ,

I was able to create a product with negative count and price values. Here is the screenshot of the issue.
image

I'm afraid that your validation routine is not sufficient enough to catch tricky cases. I would suggest that you look into validators such as `joi` or `yup` that allow you to define the shape of your models declaratively.
image

**Comment by Anisotropic** [comment]
@numatay Thanks. Nice case) I want to keep these studying tasks as simple as possible. Of course joi and any ORM are a must in a real work.

**Comment by numatay** [comment]
Cross-check review results:
- [x] TASK 4.1 is implemented. (Database, table creation scripts are provided). 
- [x] TASK 4.2 is implemented lambda links are provided and returns data
- [x] TASK 4.3 is implemented lambda links are provided and products is stored in DB
- [x]  Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend.
- [x] +1 - POST/products lambda functions returns error 400 status code if product data is invalid ()
- [x] +1 - All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
- [ ] +1 - All lambdas do console.log for each incoming requests and their arguments
- [ ] +1 - Transaction based creation of product 

**Points earned**:  _7_ pts

**Comment by LittleCryingGirl** [comment]
Hi! You saying "No extra shit in logs!" and I'm respect that, but I'm really interested how to debug, because there is no useful info in CloudWatch

**Comment by LittleCryingGirl** [comment]
minor comment: I saw that you change USD to RUB, I think you might do this at create page also) at input label -> Price($)

**Review by LittleCryingGirl — APPROVED** [review]

**Review by numatay — APPROVED** [review]

**Comment by Anisotropic** [comment]
> Hi! You saying "No extra shit in logs!" and I'm respect that, but I'm really interested how to debug, because there is no useful info in CloudWatch
> Anyway, we do dev stage, I think it might have some logs

You can use console.log(event) for this purpose

**Comment by Anisotropic** [comment]
> minor comment: I saw that you change USD to RUB, I think you might do this at create page also) at input label -> Price($)

Yeah, I saw this. This is inconsistency in FE code. I don't care much about it.

**Comment by numatay** [comment]
> @numatay Thanks. Nice case) I want to keep these studying tasks as simple as possible. Of course joi and any ORM are a must in a real work.

@Anisotropic, I didn't deduct 1 point for this case, however, it is clear that your function should return a response with HTTP status code 400 (Bad request). I hope you'll fix that bug by the next task.

**Pull request merged**
